apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', 'echo Hello Otus! && sleep 3600']
    env:
    - name: MY_VARIABLE
      value: my_value