---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config-map
data:
  myKey: myValue
  anotherKey: anotherValue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: myapp
  template:
    metadata: 
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: busybox
        command: ['sh', '-c', 'echo Hello Otus! && sleep 3600']
        env:
        - name: MY_VARIABLE
          valueFrom:
            configMapKeyRef:
              name: my-config-map
              key: myKey