apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: myapp
  template:
    metadata: 
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: busybox
        command: ['sh', '-c', 'echo Hello Otus! && sleep 3600']
        livenessProbe:
          exec:
            command:
            - echo
            - test
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 10