apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: myapp
    environment: test
  annotations:
    git-commit: a1b2c3d
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', 'echo Hello Otus! && sleep 3600']

