apiVersion: v1
kind: Pod
metadata:
  name: test-empty
spec:
  containers:
    - name: test-container
      image: nginx
      volumeMounts:
      - mountPath: /cache
        name: cache-volume
      resources:
  volumes:
    - name: cache-volume
      emptyDir:
        medium: Memory