---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
    - name: web-server
      image: nginx
      volumeMounts:
      - name: config
        mountPath: /etc/nginx/conf.d
        readOnly: true
      resources:
  volumes:
  - name: config
    configMap:
      name: config-nginx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-nginx
data:
  site.conf: |
    server {
      listen       80
      server_name  www.site.com

      gzip on;
      gzip_types text/plain application/xml;

      location / {
        root  /usr/share/nginx/html;
        index index.html index.htm;
      }
    }