kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sdd
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  zone: us-central1-c
reclaimPolicy: Retain
volumeBindingMode: Immediate