---
#Playbook для запуска докер-контейнера на хосте
#
# hosts - явный хост, где будет запущен этот плэйбук (инвентори файл не нужен)
# remote-user - пользователь, под которым это всё крутиться
# gather_facts - инфа о таргет сервака, иногда бывает нужна для дебага 
# vars - наши переменные, их мало - так что отдельного файла нет
# roles - роль, которая будет применена к серваку

- hosts: vm-name
  remote_user: docker
  gather_facts: false
  vars:
    image_tag: latest

  roles:
    - docker