image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
  - build
  - test
  - run

before_script:
  - 'dotnet --version' 

build:
  stage: build
  script:
    - 'dotnet build'

tests:
  stage: test
  script:
    - 'dotnet test'

run:
  stage: run
  script:
    - 'dotnet run'
  when: manual
  